# Generated by Django 4.1.7 on 2023-06-23 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('release_date', models.DateField(default=datetime.date(2023, 6, 23))),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
